# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionLabel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NDB_NO', models.PositiveIntegerField(default=-1, verbose_name='National Database Number')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('protein_per_100g', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Protein(g) Per 100g')),
                ('carb_per_100g', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Carbohydrate, by difference(g) Per 100g')),
                ('fat_per_100g', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Fat(g) Per 100g')),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
